version: '3.1'
services:  
  client:
    image: rpc-client:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      APP_SUM_SERVER: "http://server:8081"

  server:
    image: rpc-server:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081